-- Online Lottery PostgreSQL baseline.
-- Money is stored as integer cents. Personally identifiable fields store ciphertext plus a lookup hash.

CREATE TABLE users (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_no                 varchar(32) NOT NULL UNIQUE,
    mobile_country_code     varchar(8),
    mobile_encrypted        text,
    mobile_hash             varchar(128) UNIQUE,
    nickname                varchar(64) NOT NULL,
    avatar_url              text,
    status                  varchar(24) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('PENDING', 'ACTIVE', 'FROZEN', 'CLOSED')),
    kyc_status              varchar(24) NOT NULL DEFAULT 'UNVERIFIED' CHECK (kyc_status IN ('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED')),
    risk_level              varchar(16) NOT NULL DEFAULT 'LOW' CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'BLOCKED')),
    registered_at           timestamptz NOT NULL DEFAULT now(),
    last_login_at           timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    version                 bigint NOT NULL DEFAULT 0
);

CREATE TABLE user_identities (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 bigint NOT NULL UNIQUE REFERENCES users(id),
    real_name_encrypted     text NOT NULL,
    id_type                 varchar(24) NOT NULL,
    id_number_encrypted     text NOT NULL,
    id_number_hash          varchar(128) NOT NULL UNIQUE,
    birth_date              date NOT NULL,
    status                  varchar(24) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED')),
    verified_at             timestamptz,
    rejection_reason        varchar(256),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_devices (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 bigint NOT NULL REFERENCES users(id),
    device_fingerprint_hash varchar(128) NOT NULL,
    platform                varchar(16) NOT NULL CHECK (platform IN ('ANDROID', 'IOS', 'DESKTOP', 'WEB')),
    app_version             varchar(32),
    push_token_encrypted    text,
    trusted                 boolean NOT NULL DEFAULT false,
    first_seen_at           timestamptz NOT NULL DEFAULT now(),
    last_seen_at            timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, device_fingerprint_hash)
);

CREATE TABLE auth_sessions (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 bigint NOT NULL REFERENCES users(id),
    device_id               bigint REFERENCES user_devices(id),
    refresh_token_hash      varchar(128) NOT NULL UNIQUE,
    issued_at               timestamptz NOT NULL DEFAULT now(),
    expires_at              timestamptz NOT NULL,
    revoked_at              timestamptz,
    revoke_reason           varchar(128),
    CHECK (expires_at > issued_at)
);

CREATE TABLE user_bank_cards (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 bigint NOT NULL REFERENCES users(id),
    bank_code               varchar(32) NOT NULL,
    card_token_encrypted    text NOT NULL,
    card_token_hash         varchar(128) NOT NULL,
    card_last4              char(4) NOT NULL,
    holder_name_encrypted   text NOT NULL,
    status                  varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED', 'EXPIRED')),
    is_default              boolean NOT NULL DEFAULT false,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, card_token_hash)
);

CREATE TABLE user_risk_profiles (
    user_id                 bigint PRIMARY KEY REFERENCES users(id),
    risk_score              integer NOT NULL DEFAULT 0 CHECK (risk_score BETWEEN 0 AND 1000),
    risk_level              varchar(16) NOT NULL DEFAULT 'LOW' CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'BLOCKED')),
    flags                   jsonb NOT NULL DEFAULT '{}'::jsonb,
    last_evaluated_at       timestamptz,
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE lottery_games (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                    varchar(32) NOT NULL UNIQUE,
    name                    varchar(64) NOT NULL,
    category                varchar(24) NOT NULL CHECK (category IN ('SPORTS', 'NUMBER')),
    sport_type              varchar(24),
    status                  varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SUSPENDED', 'RETIRED')),
    sales_enabled           boolean NOT NULL DEFAULT false,
    display_order           integer NOT NULL DEFAULT 0,
    config                  jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    CHECK ((category = 'SPORTS' AND sport_type IS NOT NULL) OR category = 'NUMBER')
);

CREATE TABLE lottery_play_types (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id                 bigint NOT NULL REFERENCES lottery_games(id),
    code                    varchar(48) NOT NULL,
    name                    varchar(64) NOT NULL,
    rule_version            integer NOT NULL DEFAULT 1 CHECK (rule_version > 0),
    unit_price_cents        bigint NOT NULL CHECK (unit_price_cents > 0),
    max_multiple            integer NOT NULL DEFAULT 99 CHECK (max_multiple > 0),
    status                  varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SUSPENDED', 'RETIRED')),
    rules                   jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (game_id, code, rule_version)
);

CREATE TABLE lottery_draws (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id                 bigint NOT NULL REFERENCES lottery_games(id),
    issue_no                varchar(32) NOT NULL,
    sale_start_at           timestamptz NOT NULL,
    sale_end_at             timestamptz NOT NULL,
    draw_at                 timestamptz NOT NULL,
    status                  varchar(24) NOT NULL DEFAULT 'SCHEDULED' CHECK (status IN ('SCHEDULED', 'ON_SALE', 'SALES_CLOSED', 'DRAWING', 'PUBLISHED', 'SETTLED', 'CANCELLED')),
    sales_cents             bigint CHECK (sales_cents >= 0),
    jackpot_cents           bigint CHECK (jackpot_cents >= 0),
    result_checksum         varchar(128),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (game_id, issue_no),
    CHECK (sale_start_at < sale_end_at AND sale_end_at <= draw_at)
);

CREATE TABLE lottery_draw_numbers (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draw_id                 bigint NOT NULL REFERENCES lottery_draws(id),
    zone                    varchar(24) NOT NULL DEFAULT 'MAIN',
    position                integer NOT NULL CHECK (position > 0),
    number_value            varchar(8) NOT NULL,
    UNIQUE (draw_id, zone, position)
);

CREATE TABLE sports_competitions (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_code           varchar(64) NOT NULL UNIQUE,
    name                    varchar(96) NOT NULL,
    short_name              varchar(32),
    sport_type              varchar(24) NOT NULL,
    country_code            char(2),
    logo_url                text,
    status                  varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sports_teams (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_code           varchar(64) NOT NULL UNIQUE,
    name                    varchar(96) NOT NULL,
    short_name              varchar(32),
    sport_type              varchar(24) NOT NULL,
    country_code            char(2),
    crest_url               text,
    crest_checksum          varchar(128),
    status                  varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sports_matches (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_match_id       varchar(64) NOT NULL UNIQUE,
    competition_id          bigint NOT NULL REFERENCES sports_competitions(id),
    home_team_id            bigint NOT NULL REFERENCES sports_teams(id),
    away_team_id            bigint NOT NULL REFERENCES sports_teams(id),
    business_date           date NOT NULL,
    kickoff_at              timestamptz NOT NULL,
    sale_end_at             timestamptz,
    status                  varchar(24) NOT NULL DEFAULT 'SCHEDULED' CHECK (status IN ('SCHEDULED', 'ON_SALE', 'CLOSED', 'LIVE', 'FINISHED', 'CANCELLED', 'POSTPONED')),
    home_score              integer CHECK (home_score >= 0),
    away_score              integer CHECK (away_score >= 0),
    metadata                jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    CHECK (home_team_id <> away_team_id)
);

CREATE TABLE match_markets (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id                bigint NOT NULL REFERENCES sports_matches(id),
    play_type_id            bigint NOT NULL REFERENCES lottery_play_types(id),
    market_code             varchar(48) NOT NULL,
    line_value              numeric(10, 3),
    status                  varchar(16) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'SUSPENDED', 'CLOSED', 'SETTLED', 'VOID')),
    version                 bigint NOT NULL DEFAULT 0,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (match_id, market_code, line_value)
);

CREATE TABLE market_selections (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id               bigint NOT NULL REFERENCES match_markets(id),
    selection_code          varchar(32) NOT NULL,
    selection_name          varchar(64) NOT NULL,
    result                  varchar(16) NOT NULL DEFAULT 'UNSET' CHECK (result IN ('UNSET', 'WIN', 'LOSE', 'PUSH', 'VOID')),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (market_id, selection_code)
);

CREATE TABLE odds_snapshots (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selection_id            bigint NOT NULL REFERENCES market_selections(id),
    odds_decimal            numeric(12, 4) NOT NULL CHECK (odds_decimal > 1),
    status                  varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
    source                  varchar(32) NOT NULL,
    valid_from              timestamptz NOT NULL,
    received_at             timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE bet_orders (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no                varchar(40) NOT NULL UNIQUE,
    user_id                 bigint NOT NULL REFERENCES users(id),
    game_id                 bigint NOT NULL REFERENCES lottery_games(id),
    order_type              varchar(24) NOT NULL CHECK (order_type IN ('SPORTS_SINGLE', 'SPORTS_PARLAY', 'NUMBER_SINGLE', 'NUMBER_CHASE')),
    status                  varchar(24) NOT NULL DEFAULT 'CREATED' CHECK (status IN ('CREATED', 'PAYMENT_PENDING', 'PAID', 'TICKETING', 'TICKETED', 'PARTIAL_TICKETED', 'FAILED', 'CANCELLED', 'SETTLING', 'SETTLED', 'REFUNDED')),
    total_stake_cents       bigint NOT NULL CHECK (total_stake_cents > 0),
    potential_payout_cents  bigint CHECK (potential_payout_cents >= 0),
    currency                char(3) NOT NULL DEFAULT 'CNY',
    client_request_id       varchar(64) NOT NULL,
    submitted_at            timestamptz,
    sale_deadline_at        timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    version                 bigint NOT NULL DEFAULT 0,
    UNIQUE (user_id, client_request_id)
);

CREATE TABLE bet_order_items (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                bigint NOT NULL REFERENCES bet_orders(id),
    play_type_id            bigint NOT NULL REFERENCES lottery_play_types(id),
    draw_id                 bigint REFERENCES lottery_draws(id),
    item_no                 integer NOT NULL CHECK (item_no > 0),
    units                   integer NOT NULL CHECK (units > 0),
    multiple                integer NOT NULL DEFAULT 1 CHECK (multiple > 0),
    stake_cents             bigint NOT NULL CHECK (stake_cents > 0),
    content                 jsonb NOT NULL,
    status                  varchar(24) NOT NULL DEFAULT 'CREATED' CHECK (status IN ('CREATED', 'ACCEPTED', 'TICKETED', 'FAILED', 'CANCELLED', 'SETTLED', 'REFUNDED')),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (order_id, item_no)
);

CREATE TABLE bet_selections (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id           bigint NOT NULL REFERENCES bet_order_items(id),
    match_id                bigint REFERENCES sports_matches(id),
    market_selection_id     bigint REFERENCES market_selections(id),
    odds_snapshot_id        bigint REFERENCES odds_snapshots(id),
    selected_value          varchar(64) NOT NULL,
    accepted_odds_decimal   numeric(12, 4),
    created_at              timestamptz NOT NULL DEFAULT now(),
    CHECK ((match_id IS NULL AND market_selection_id IS NULL) OR (match_id IS NOT NULL AND market_selection_id IS NOT NULL))
);

CREATE TABLE ticket_orders (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                bigint NOT NULL REFERENCES bet_orders(id),
    ticket_order_no         varchar(40) NOT NULL UNIQUE,
    channel                 varchar(32) NOT NULL,
    status                  varchar(24) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SUBMITTED', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILED', 'CANCELLED')),
    amount_cents            bigint NOT NULL CHECK (amount_cents > 0),
    idempotency_key         varchar(80) NOT NULL UNIQUE,
    attempt_count           integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    last_error_code         varchar(64),
    last_error_message      varchar(256),
    submitted_at            timestamptz,
    completed_at            timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE official_tickets (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_order_id         bigint NOT NULL REFERENCES ticket_orders(id),
    order_item_id           bigint NOT NULL REFERENCES bet_order_items(id),
    official_ticket_no      varchar(80) NOT NULL UNIQUE,
    status                  varchar(24) NOT NULL DEFAULT 'ISSUED' CHECK (status IN ('ISSUED', 'WIN', 'LOSE', 'VOID', 'REFUNDED')),
    stake_cents             bigint NOT NULL CHECK (stake_cents > 0),
    ticket_payload          jsonb NOT NULL,
    issued_at               timestamptz NOT NULL,
    created_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE order_status_histories (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                bigint NOT NULL REFERENCES bet_orders(id),
    from_status             varchar(24),
    to_status               varchar(24) NOT NULL,
    reason_code             varchar(64),
    reason_message          varchar(256),
    operator_type           varchar(24) NOT NULL DEFAULT 'SYSTEM',
    operator_id             varchar(64),
    created_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE chase_plans (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chase_no                varchar(40) NOT NULL UNIQUE,
    user_id                 bigint NOT NULL REFERENCES users(id),
    game_id                 bigint NOT NULL REFERENCES lottery_games(id),
    play_type_id            bigint NOT NULL REFERENCES lottery_play_types(id),
    status                  varchar(24) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'PAUSED', 'COMPLETED', 'STOPPED', 'FAILED')),
    total_issues            integer NOT NULL CHECK (total_issues > 0),
    completed_issues        integer NOT NULL DEFAULT 0 CHECK (completed_issues >= 0),
    per_issue_stake_cents   bigint NOT NULL CHECK (per_issue_stake_cents > 0),
    total_stake_cents       bigint NOT NULL CHECK (total_stake_cents > 0),
    stop_after_win          boolean NOT NULL DEFAULT true,
    selection_content       jsonb NOT NULL,
    client_request_id       varchar(64) NOT NULL,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    CHECK (completed_issues <= total_issues),
    CHECK (total_stake_cents = per_issue_stake_cents * total_issues),
    UNIQUE (user_id, client_request_id)
);

CREATE TABLE chase_plan_issues (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chase_plan_id           bigint NOT NULL REFERENCES chase_plans(id),
    draw_id                 bigint NOT NULL REFERENCES lottery_draws(id),
    issue_sequence          integer NOT NULL CHECK (issue_sequence > 0),
    stake_cents             bigint NOT NULL CHECK (stake_cents > 0),
    status                  varchar(24) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ORDERED', 'TICKETED', 'SKIPPED', 'FAILED', 'REFUNDED')),
    order_id                bigint UNIQUE REFERENCES bet_orders(id),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (chase_plan_id, issue_sequence),
    UNIQUE (chase_plan_id, draw_id)
);

CREATE TABLE user_favorites (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 bigint NOT NULL REFERENCES users(id),
    target_type             varchar(24) NOT NULL CHECK (target_type IN ('GAME', 'COMPETITION', 'TEAM', 'MATCH')),
    target_id               bigint NOT NULL,
    created_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, target_type, target_id)
);

CREATE TABLE wallet_accounts (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type              varchar(24) NOT NULL CHECK (owner_type IN ('USER', 'PLATFORM', 'CHANNEL')),
    owner_id                bigint NOT NULL,
    account_code            varchar(64) NOT NULL,
    account_type            varchar(32) NOT NULL CHECK (account_type IN ('AVAILABLE', 'BETTING_FROZEN', 'PRIZE', 'WITHDRAWAL_FROZEN', 'PAYMENT_PENDING', 'LOTTERY_SALES', 'PRIZE_SETTLEMENT', 'CHANNEL_CLEARING')),
    currency                char(3) NOT NULL DEFAULT 'CNY',
    status                  varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED')),
    balance_cents           bigint NOT NULL DEFAULT 0,
    version                 bigint NOT NULL DEFAULT 0,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (owner_type, owner_id, account_code)
);

CREATE TABLE wallet_transactions (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_no          varchar(48) NOT NULL UNIQUE,
    business_type           varchar(32) NOT NULL CHECK (business_type IN ('RECHARGE', 'BET_FREEZE', 'BET_CAPTURE', 'BET_UNFREEZE', 'PRIZE', 'WITHDRAW_FREEZE', 'WITHDRAW_CAPTURE', 'WITHDRAW_UNFREEZE', 'REFUND', 'ADJUSTMENT')),
    business_id             varchar(64) NOT NULL,
    idempotency_key         varchar(96) NOT NULL UNIQUE,
    status                  varchar(16) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'POSTED', 'REVERSED', 'FAILED')),
    total_cents             bigint NOT NULL CHECK (total_cents > 0),
    description             varchar(256),
    posted_at               timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (business_type, business_id)
);

CREATE TABLE accounting_entries (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id          bigint NOT NULL REFERENCES wallet_transactions(id),
    account_id              bigint NOT NULL REFERENCES wallet_accounts(id),
    line_no                 integer NOT NULL CHECK (line_no > 0),
    direction               varchar(8) NOT NULL CHECK (direction IN ('DEBIT', 'CREDIT')),
    amount_cents            bigint NOT NULL CHECK (amount_cents > 0),
    balance_after_cents     bigint NOT NULL,
    created_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (transaction_id, line_no)
);

CREATE TABLE recharge_orders (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recharge_no             varchar(40) NOT NULL UNIQUE,
    user_id                 bigint NOT NULL REFERENCES users(id),
    provider                varchar(32) NOT NULL,
    provider_order_no       varchar(80),
    amount_cents            bigint NOT NULL CHECK (amount_cents > 0),
    status                  varchar(24) NOT NULL DEFAULT 'CREATED' CHECK (status IN ('CREATED', 'PAYING', 'PAID', 'CREDITED', 'FAILED', 'CLOSED', 'REFUNDED')),
    client_request_id       varchar(64) NOT NULL,
    paid_at                 timestamptz,
    credited_at             timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, client_request_id),
    UNIQUE (provider, provider_order_no)
);

CREATE TABLE payment_callbacks (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider                varchar(32) NOT NULL,
    callback_id             varchar(128) NOT NULL,
    business_type           varchar(24) NOT NULL,
    business_no             varchar(80) NOT NULL,
    signature_valid         boolean NOT NULL,
    payload                 jsonb NOT NULL,
    processing_status       varchar(16) NOT NULL DEFAULT 'RECEIVED' CHECK (processing_status IN ('RECEIVED', 'PROCESSED', 'IGNORED', 'FAILED')),
    processed_at            timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider, callback_id)
);

CREATE TABLE withdrawal_orders (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    withdrawal_no           varchar(40) NOT NULL UNIQUE,
    user_id                 bigint NOT NULL REFERENCES users(id),
    bank_card_id            bigint NOT NULL REFERENCES user_bank_cards(id),
    amount_cents            bigint NOT NULL CHECK (amount_cents > 0),
    fee_cents               bigint NOT NULL DEFAULT 0 CHECK (fee_cents >= 0),
    status                  varchar(24) NOT NULL DEFAULT 'CREATED' CHECK (status IN ('CREATED', 'RISK_REVIEW', 'APPROVED', 'REJECTED', 'PROCESSING', 'PAID', 'FAILED', 'CANCELLED')),
    client_request_id       varchar(64) NOT NULL,
    provider_order_no       varchar(80),
    rejection_reason        varchar(256),
    completed_at            timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, client_request_id)
);

CREATE TABLE settlement_jobs (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_no                  varchar(40) NOT NULL UNIQUE,
    settlement_type         varchar(24) NOT NULL CHECK (settlement_type IN ('DRAW', 'MATCH', 'REFUND')),
    target_type             varchar(24) NOT NULL,
    target_id               bigint NOT NULL,
    status                  varchar(24) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILED')),
    idempotency_key         varchar(96) NOT NULL UNIQUE,
    started_at              timestamptz,
    completed_at            timestamptz,
    error_message           varchar(512),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE settlement_records (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_job_id       bigint NOT NULL REFERENCES settlement_jobs(id),
    order_id                bigint NOT NULL REFERENCES bet_orders(id),
    order_item_id           bigint REFERENCES bet_order_items(id),
    result                  varchar(16) NOT NULL CHECK (result IN ('WIN', 'LOSE', 'PUSH', 'VOID', 'REFUND')),
    stake_cents             bigint NOT NULL CHECK (stake_cents > 0),
    payout_cents            bigint NOT NULL DEFAULT 0 CHECK (payout_cents >= 0),
    calculation             jsonb NOT NULL,
    created_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (settlement_job_id, order_id, order_item_id)
);

CREATE TABLE prize_records (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prize_no                varchar(40) NOT NULL UNIQUE,
    user_id                 bigint NOT NULL REFERENCES users(id),
    order_id                bigint NOT NULL REFERENCES bet_orders(id),
    settlement_record_id    bigint NOT NULL REFERENCES settlement_records(id),
    gross_prize_cents       bigint NOT NULL CHECK (gross_prize_cents > 0),
    tax_cents               bigint NOT NULL DEFAULT 0 CHECK (tax_cents >= 0),
    net_prize_cents         bigint NOT NULL CHECK (net_prize_cents > 0),
    status                  varchar(24) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'CREDITED', 'HELD', 'FAILED', 'REVERSED')),
    wallet_transaction_id   bigint REFERENCES wallet_transactions(id),
    credited_at             timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    CHECK (gross_prize_cents = tax_cents + net_prize_cents),
    UNIQUE (settlement_record_id)
);

CREATE TABLE refund_records (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_no               varchar(40) NOT NULL UNIQUE,
    user_id                 bigint NOT NULL REFERENCES users(id),
    order_id                bigint NOT NULL REFERENCES bet_orders(id),
    amount_cents            bigint NOT NULL CHECK (amount_cents > 0),
    reason_code             varchar(64) NOT NULL,
    status                  varchar(24) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'CREDITED', 'FAILED', 'REVERSED')),
    wallet_transaction_id   bigint REFERENCES wallet_transactions(id),
    credited_at             timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE risk_rules (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code               varchar(64) NOT NULL UNIQUE,
    name                    varchar(96) NOT NULL,
    event_type              varchar(48) NOT NULL,
    version                 integer NOT NULL CHECK (version > 0),
    priority                integer NOT NULL DEFAULT 100,
    action                  varchar(24) NOT NULL CHECK (action IN ('ALLOW', 'CHALLENGE', 'REVIEW', 'REJECT', 'FREEZE')),
    expression              jsonb NOT NULL,
    status                  varchar(16) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE')),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE risk_events (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_no                varchar(40) NOT NULL UNIQUE,
    user_id                 bigint REFERENCES users(id),
    event_type              varchar(48) NOT NULL,
    business_type           varchar(32),
    business_id             varchar(64),
    risk_score              integer NOT NULL CHECK (risk_score BETWEEN 0 AND 1000),
    decision                varchar(24) NOT NULL CHECK (decision IN ('ALLOW', 'CHALLENGE', 'REVIEW', 'REJECT', 'FREEZE')),
    matched_rules           jsonb NOT NULL DEFAULT '[]'::jsonb,
    evidence                jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE manual_reviews (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_no               varchar(40) NOT NULL UNIQUE,
    risk_event_id           bigint NOT NULL REFERENCES risk_events(id),
    subject_type            varchar(32) NOT NULL,
    subject_id              varchar(64) NOT NULL,
    status                  varchar(24) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED')),
    assignee_id             varchar(64),
    decision_reason         varchar(512),
    decided_at              timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE notifications (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code           varchar(64) NOT NULL,
    channel                 varchar(16) NOT NULL CHECK (channel IN ('IN_APP', 'PUSH', 'SMS', 'EMAIL')),
    title                   varchar(128),
    content                 text NOT NULL,
    variables               jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_notifications (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id         bigint NOT NULL REFERENCES notifications(id),
    user_id                 bigint NOT NULL REFERENCES users(id),
    status                  varchar(16) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED')),
    sent_at                 timestamptz,
    read_at                 timestamptz,
    error_message           varchar(256),
    created_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (notification_id, user_id)
);

CREATE TABLE coupon_templates (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code           varchar(64) NOT NULL UNIQUE,
    name                    varchar(96) NOT NULL,
    discount_type           varchar(16) NOT NULL CHECK (discount_type IN ('FIXED', 'PERCENT')),
    discount_cents          bigint CHECK (discount_cents > 0),
    discount_basis_points   integer CHECK (discount_basis_points BETWEEN 1 AND 10000),
    minimum_stake_cents     bigint NOT NULL DEFAULT 0 CHECK (minimum_stake_cents >= 0),
    maximum_discount_cents  bigint CHECK (maximum_discount_cents > 0),
    applicable_game_codes   jsonb NOT NULL DEFAULT '[]'::jsonb,
    valid_days              integer CHECK (valid_days > 0),
    starts_at               timestamptz,
    ends_at                 timestamptz,
    status                  varchar(16) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'ACTIVE', 'PAUSED', 'EXPIRED')),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    CHECK (
        (discount_type = 'FIXED' AND discount_cents IS NOT NULL AND discount_basis_points IS NULL)
        OR (discount_type = 'PERCENT' AND discount_basis_points IS NOT NULL AND discount_cents IS NULL)
    ),
    CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
);

CREATE TABLE user_coupons (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_no               varchar(48) NOT NULL UNIQUE,
    user_id                 bigint NOT NULL REFERENCES users(id),
    template_id             bigint NOT NULL REFERENCES coupon_templates(id),
    status                  varchar(16) NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'LOCKED', 'USED', 'EXPIRED', 'VOID')),
    locked_order_id         bigint REFERENCES bet_orders(id),
    used_order_id           bigint REFERENCES bet_orders(id),
    issued_at               timestamptz NOT NULL DEFAULT now(),
    expires_at              timestamptz NOT NULL,
    used_at                 timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE referral_codes (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id           bigint NOT NULL REFERENCES users(id),
    referral_code           varchar(32) NOT NULL UNIQUE,
    status                  varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
    created_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (owner_user_id)
);

CREATE TABLE referral_rewards (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reward_no               varchar(40) NOT NULL UNIQUE,
    referrer_user_id        bigint NOT NULL REFERENCES users(id),
    referred_user_id        bigint NOT NULL REFERENCES users(id),
    reward_type             varchar(24) NOT NULL CHECK (reward_type IN ('REGISTRATION', 'FIRST_RECHARGE', 'FIRST_BET', 'CAMPAIGN')),
    reward_cents            bigint NOT NULL CHECK (reward_cents > 0),
    status                  varchar(24) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'CREDITED', 'REJECTED', 'REVERSED')),
    wallet_transaction_id   bigint REFERENCES wallet_transactions(id),
    created_at              timestamptz NOT NULL DEFAULT now(),
    credited_at             timestamptz,
    CHECK (referrer_user_id <> referred_user_id),
    UNIQUE (referred_user_id, reward_type)
);

CREATE TABLE user_growth_accounts (
    user_id                 bigint PRIMARY KEY REFERENCES users(id),
    level_code              varchar(24) NOT NULL DEFAULT 'VIP0',
    growth_points           bigint NOT NULL DEFAULT 0 CHECK (growth_points >= 0),
    version                 bigint NOT NULL DEFAULT 0,
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_growth_entries (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 bigint NOT NULL REFERENCES users(id),
    business_type           varchar(32) NOT NULL,
    business_id             varchar(64) NOT NULL,
    points_delta            bigint NOT NULL CHECK (points_delta <> 0),
    balance_after           bigint NOT NULL CHECK (balance_after >= 0),
    description             varchar(256),
    created_at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (business_type, business_id, user_id)
);

CREATE TABLE help_articles (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code           varchar(48) NOT NULL,
    slug                    varchar(96) NOT NULL UNIQUE,
    title                   varchar(160) NOT NULL,
    summary                 varchar(320),
    content_markdown        text NOT NULL,
    display_order           integer NOT NULL DEFAULT 0,
    status                  varchar(16) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    published_at            timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE responsible_gaming_limits (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 bigint NOT NULL REFERENCES users(id),
    limit_type              varchar(24) NOT NULL CHECK (limit_type IN ('DAILY_STAKE', 'WEEKLY_STAKE', 'MONTHLY_STAKE', 'DAILY_RECHARGE', 'SESSION_DURATION')),
    limit_value             bigint NOT NULL CHECK (limit_value > 0),
    effective_from          timestamptz NOT NULL DEFAULT now(),
    effective_to            timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    CHECK (effective_to IS NULL OR effective_to > effective_from),
    UNIQUE (user_id, limit_type, effective_from)
);

CREATE TABLE self_exclusions (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 bigint NOT NULL REFERENCES users(id),
    starts_at               timestamptz NOT NULL,
    ends_at                 timestamptz,
    reason                  varchar(256),
    status                  varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'EXPIRED', 'REVOKED')),
    created_at              timestamptz NOT NULL DEFAULT now(),
    CHECK (ends_at IS NULL OR ends_at > starts_at)
);

CREATE TABLE audit_logs (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id                varchar(64) NOT NULL,
    actor_type              varchar(24) NOT NULL,
    actor_id                varchar(64),
    action                  varchar(96) NOT NULL,
    resource_type           varchar(48) NOT NULL,
    resource_id             varchar(64),
    client_ip_hash          varchar(128),
    before_data             jsonb,
    after_data              jsonb,
    result                  varchar(16) NOT NULL CHECK (result IN ('SUCCESS', 'FAILURE')),
    created_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE operation_logs (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id             varchar(64) NOT NULL,
    operation_type          varchar(64) NOT NULL,
    target_type             varchar(48) NOT NULL,
    target_id               varchar(64) NOT NULL,
    reason                  varchar(512) NOT NULL,
    approval_no             varchar(64),
    payload                 jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_status ON users (status, created_at DESC);
CREATE INDEX idx_user_devices_user_last_seen ON user_devices (user_id, last_seen_at DESC);
CREATE INDEX idx_auth_sessions_user_expiry ON auth_sessions (user_id, expires_at DESC);
CREATE UNIQUE INDEX uq_user_bank_cards_default ON user_bank_cards (user_id) WHERE is_default AND status = 'ACTIVE';
CREATE INDEX idx_draws_game_sale_end ON lottery_draws (game_id, status, sale_end_at);
CREATE INDEX idx_matches_business_status ON sports_matches (business_date, status, kickoff_at);
CREATE INDEX idx_matches_competition_kickoff ON sports_matches (competition_id, kickoff_at);
CREATE INDEX idx_markets_match_status ON match_markets (match_id, status);
CREATE UNIQUE INDEX uq_markets_without_line ON match_markets (match_id, market_code) WHERE line_value IS NULL;
CREATE INDEX idx_odds_selection_valid_from ON odds_snapshots (selection_id, valid_from DESC);
CREATE INDEX idx_orders_user_created ON bet_orders (user_id, created_at DESC);
CREATE INDEX idx_orders_status_deadline ON bet_orders (status, sale_deadline_at);
CREATE INDEX idx_order_items_order_status ON bet_order_items (order_id, status);
CREATE INDEX idx_ticket_orders_order_status ON ticket_orders (order_id, status);
CREATE INDEX idx_order_history_order_created ON order_status_histories (order_id, created_at);
CREATE INDEX idx_chase_plans_user_created ON chase_plans (user_id, created_at DESC);
CREATE INDEX idx_chase_issues_plan_status ON chase_plan_issues (chase_plan_id, status, issue_sequence);
CREATE INDEX idx_user_favorites_user_created ON user_favorites (user_id, created_at DESC);
CREATE INDEX idx_wallet_accounts_owner ON wallet_accounts (owner_type, owner_id, status);
CREATE INDEX idx_wallet_transactions_business ON wallet_transactions (business_type, business_id);
CREATE INDEX idx_accounting_entries_account_created ON accounting_entries (account_id, created_at DESC);
CREATE INDEX idx_recharge_user_created ON recharge_orders (user_id, created_at DESC);
CREATE INDEX idx_withdrawal_user_created ON withdrawal_orders (user_id, created_at DESC);
CREATE INDEX idx_settlement_records_order ON settlement_records (order_id, order_item_id);
CREATE UNIQUE INDEX uq_settlement_order_level ON settlement_records (settlement_job_id, order_id) WHERE order_item_id IS NULL;
CREATE INDEX idx_prizes_user_created ON prize_records (user_id, created_at DESC);
CREATE INDEX idx_refunds_order ON refund_records (order_id, created_at DESC);
CREATE INDEX idx_risk_events_user_created ON risk_events (user_id, created_at DESC);
CREATE INDEX idx_manual_reviews_status_created ON manual_reviews (status, created_at);
CREATE INDEX idx_user_notifications_inbox ON user_notifications (user_id, status, created_at DESC);
CREATE INDEX idx_user_coupons_wallet ON user_coupons (user_id, status, expires_at);
CREATE INDEX idx_referral_rewards_referrer ON referral_rewards (referrer_user_id, status, created_at DESC);
CREATE INDEX idx_growth_entries_user_created ON user_growth_entries (user_id, created_at DESC);
CREATE INDEX idx_help_articles_category ON help_articles (category_code, status, display_order);
CREATE INDEX idx_self_exclusions_active ON self_exclusions (user_id, starts_at, ends_at) WHERE status = 'ACTIVE';
CREATE INDEX idx_audit_logs_resource ON audit_logs (resource_type, resource_id, created_at DESC);

CREATE OR REPLACE FUNCTION validate_balanced_wallet_transaction()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    debit_total bigint;
    credit_total bigint;
    entry_count integer;
    should_validate boolean;
BEGIN
    should_validate = NEW.status = 'POSTED';
    IF TG_OP = 'UPDATE' THEN
        should_validate = should_validate AND OLD.status IS DISTINCT FROM 'POSTED';
    END IF;

    IF should_validate THEN
        SELECT
            COALESCE(SUM(amount_cents) FILTER (WHERE direction = 'DEBIT'), 0),
            COALESCE(SUM(amount_cents) FILTER (WHERE direction = 'CREDIT'), 0),
            COUNT(*)
        INTO debit_total, credit_total, entry_count
        FROM accounting_entries
        WHERE transaction_id = NEW.id;

        IF entry_count < 2 OR debit_total <> credit_total OR debit_total <> NEW.total_cents THEN
            RAISE EXCEPTION 'wallet transaction % is not balanced: debit %, credit %, total %',
                NEW.transaction_no, debit_total, credit_total, NEW.total_cents;
        END IF;

        NEW.posted_at = COALESCE(NEW.posted_at, now());
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_balanced_wallet_transaction
BEFORE INSERT OR UPDATE OF status ON wallet_transactions
FOR EACH ROW EXECUTE FUNCTION validate_balanced_wallet_transaction();

CREATE OR REPLACE FUNCTION protect_posted_accounting_entries()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_transaction_id bigint;
    transaction_status varchar(16);
BEGIN
    IF TG_OP = 'DELETE' THEN
        target_transaction_id = OLD.transaction_id;
    ELSE
        target_transaction_id = NEW.transaction_id;
    END IF;
    SELECT status INTO transaction_status FROM wallet_transactions WHERE id = target_transaction_id;
    IF transaction_status = 'POSTED' THEN
        RAISE EXCEPTION 'accounting entries for posted transaction % are immutable', target_transaction_id;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_protect_posted_accounting_entries
BEFORE INSERT OR UPDATE OR DELETE ON accounting_entries
FOR EACH ROW EXECUTE FUNCTION protect_posted_accounting_entries();
